### ISSUE TITLE
docs and demo needed

### ISSUE THREAD

**Issue by GodGavin** [goa-systems/Goa.Systems.Blazor#1]
。

**Comment by andreasgottardi** [comment]
Hello, sure, feel free to use it!
The setup instructions are stored as markdown files in the folder `Goa.Systems.Blazor.Docs` and there is a rough overview over the functionality in `Goa.Systems.Blazor.Presentation` which is a [Reveal.JS](https://revealjs.com) presentation and can be run with the standard Reveal.JS commands.

I do not have a demo running as it can easily be run on a local machine by doing it with `dotnet run` in the solution folder.

**Comment by GodGavin** [comment]
Thanks,and i want to know how does it work
 Do I need to write C#? I don't understand C# or JavaScript at all, and I'm too lazy to learn these. I only know Golang.

**Comment by andreasgottardi** [comment]
I'm afraid if you don't use C# or JavaScript this example is not suited for you. You need these skills to use it.
